config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users
  resources :collection_items
  resources :collections do
    resources :collection_items, path: :items
  end

  # Defines the root path route ("/")
  root to: "collections#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  attr_accessor :user
  has_many :user_collections, dependent: :destroy
  has_many :users, through: :user_collections
  has_many :collection_items, dependent: :destroy

  before_validation :add_user_to_collection

  def add_user_to_collection
    user_collections.build(user: user, role: :owner)
  end

  def minimum_role?(user, role)
    role_id = UserCollection.roles[role]
    roles = UserCollection.roles.select { _2 >= role_id }
    roles.include? user_collections.find_by(user: user)&.role
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[show edit update destroy]

  # GET /collections
  def index
    @collections = policy_scope(Collection).all
  end

  # GET /collections/1
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new(user: current_user)
    authorize @collection
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  def create
    @collection = Collection.new(collection_params.merge(user: current_user))
    authorize @collection

    if @collection.save
      redirect_to @collection, notice: "Collection was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /collections/1
  def update
    if @collection.update(collection_params)
      redirect_to @collection, notice: "Collection was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy
    redirect_to collections_url, notice: "Collection was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.find(params[:id])
    authorize @collection
  end

  # Only allow a list of trusted parameters through.
  def collection_params
    params.require(:collection).permit(:title, :description, :rules)
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div class="card" id="<%= dom_id(collection) %>">
  <div class="card-header">
    <h3 class="card-title"><%= collection.title %></h3>
  </div>
  <div class="card-body">
    <% collection.collection_items.with_images.map{ _1.images.first }.first(20).each do |image| %>
      <%= image_tag image.variant(:thumb), class: 'img-thumbnail rounded' %>
    <% end %>
    <p class="card-text"><%= collection.description %></p>
    <%= link_to collection_collection_items_path(collection), class: 'btn btn-primary p' do %>
      View
    <% end %>
  </div>
</div>

app/views/collections/_form.html.erb
<%= simple_form_for(@collection) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :rules %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Show this collection", @collection %> |
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Collections</h1>

<div id="collections" class="row">
  <% @collections.each do |collection| %>
    <div class="col-12 col-md-6">
    <%= render collection %>
    </div>
  <% end %>
</div>

<%= link_to "New collection", new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @collection %>

<div>
  <%= link_to "Edit this collection", edit_collection_path(@collection) %> |
  <%= link_to "Back to collections", collections_path %>

  <%= button_to "Destroy this collection", @collection, method: :delete %>
</div>