config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users
  resources :collection_items
  resources :collections do
    resources :collection_items, path: :items
  end

  # Defines the root path route ("/")
  root to: "collections#index"
end

app/models/collection_item.rb
class CollectionItem < ApplicationRecord
  has_paper_trail
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_fill: [50, 50]
  end

  scope :with_images, -> { joins(:images_attachments).uniq }

  belongs_to :collection
  enum availability: {available: 0, unavailable: 1, sold: 2}, _default: :available
end

app/controllers/collection_items_controller.rb
class CollectionItemsController < ApplicationController
  before_action :set_collection_item, only: %i[show edit update destroy]
  before_action :set_collection, only: %i[index new create]
  before_action :set_paper_trail_whodunnit

  # GET /collection_items
  def index
    @collection_items = policy_scope(CollectionItem)
  end

  # GET /collection_items/1
  def show
  end

  # GET /collection_items/new
  def new
    @collection_item = CollectionItem.new(collection: @collection, availability: :available)
    authorize @collection_item
  end

  # GET /collection_items/1/edit
  def edit
  end

  # POST /collection_items
  def create
    @collection_item = CollectionItem.new(collection_item_params)
    authorize @collection_item

    if @collection_item.save
      redirect_to @collection_item, notice: "Collection item was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /collection_items/1
  def update
    if @collection_item.update(collection_item_params)
      redirect_to @collection_item, notice: "Collection item was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /collection_items/1
  def destroy
    @collection_item.destroy!
    redirect_to collection_items_url, notice: "Collection item was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_collection_item
    @collection_item = CollectionItem.find(params[:id])
    authorize @collection_item
  end

  def set_collection
    @collection = Collection.find_by(id: params[:collection_id]) || policy_scope(Collection)
  end

  # Only allow a list of trusted parameters through.
  def collection_item_params
    params.require(:collection_item).permit(:collection_id, :title, :description, :value, :height_mm, :width_mm, :depth_mm, :availability, images: [])
  end
end

app/helpers/collection_items_helper.rb
module CollectionItemsHelper
end

app/views/collection_items/_collection_item.html.erb
<div class="card collection-item-card" id="<%= dom_id(collection_item) %>">
  <% if collection_item.images.length > 1 %>
    <% carousel_id = dom_id(collection_item) + '_carousel' %>
    <div id="<%= carousel_id %>" class="carousel slide">
      <div class="carousel-inner">
        <% collection_item.images.each do |image| %>
          <a class="carousel-item <%= 'active' if image == collection_item.images.first %>" href="<%= url_for(image) %>" target="_blank">
            <%= image_tag url_for(image), class: 'd-block w-100 card-img-top' %>
          </a>
        <% end %>
      </div>
      <buitton class="carousel-control-prev" data-bs-target="#<%= carousel_id %>" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </buitton>
      <button class="carousel-control-next" data-bs-target="#<%= carousel_id %>" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  <% else %>
    <a href="<%= url_for(collection_item.images.first) %>" target="_blank">
      <%= image_tag url_for(collection_item.images.first), class: 'card-img-top', alt: collection_item.title %>
    </a>
  <% end %>
  <div class="card-body">
    <h5 class="card-title text-truncate"><%= collection_item.title %></h5>
    <p class="card-text text-truncate"><%= collection_item.description %></p>
    <%= link_to collection_item, class: 'btn btn-primary' do %>
      View
    <% end %>
  </div>
</div>

app/views/collection_items/_form.html.erb
<%= simple_form_for([@collection, @collection_item]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :collection_id, as: :hidden %>
    <div
      class="dropzone dropzone-default dz-clickable"
      data-controller="dropzone"
      data-dropzone-max-file-size="10"
      data-dropzone-max-files="10"
      data-dropzone-accepted-files="image/*">
      <%=
        f.input(:images,
                input_html: {
                  multiple: true,
                  direct_upload: true,
                  data: { target: 'dropzone.input' }
                })
      %>
      <div class="dropzone-msg dz-message needsclick">
        <h3 class="dropzone-msg-title">
          <%= t('.images.drop_title') %>
        </h3>
        <span class="dropzone-msg-desc">
          <%= t('.images.drop_description') %>
        </span>
      </div>
    </div>
    <%= f.input :title %>
    <%= f.input :description %>
    <%#= f.input :value %>
    <%#= f.input :height_mm %>
    <%#= f.input :width_mm %>
    <%#= f.input :depth_mm %>
    <%#= f.input :availability, collection: CollectionItem.availabilities.keys, include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/collection_items/_new_collection_item.html.erb
<div class="card collection-item-card h-100">
  <div class="card-body text-center d-flex justify-content-center flex-column">
    <%= link_to new_collection_collection_item_path(@collection) do %>
      <i class="bi bi-plus "></i>
      <h3><%= t('.title') %></h3>
    <% end %>
  </div>
</div>

app/views/collection_items/edit.html.erb
<h1>Editing collection item</h1>

<%= render "form", collection_item: @collection_item %>

<br>

<div>
  <%= link_to "Show this collection item", @collection_item %> |
  <%= link_to "Back to collection items", collection_items_path %>
</div>

app/views/collection_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Collection items</h1>

<div id="collection_items" class="row">
  <% @collection_items.each do |collection_item| %>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3 mb-sm-0">
      <%= render collection_item %>
    </div>
  <% end %>
  <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3 mb-sm-0">
    <%= render 'new_collection_item' %>
  </div>
</div>

<%= link_to "New collection item", new_collection_collection_item_path(@collection) %>

app/views/collection_items/new.html.erb
<h1>New collection item</h1>

<%= render "form", collection_item: @collection_item %>

<br>

<div>
  <%= link_to "Back to collection items", collection_items_path %>
</div>

app/views/collection_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @collection_item %>

<div>
  <%= link_to "Edit this collection item", edit_collection_item_path(@collection_item) %> |
  <%= link_to "Back to collection items", collection_collection_items_path(@collection_item.collection) %>

  <%= button_to "Destroy this collection item", @collection_item, method: :delete %>
</div>